### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by FoxBotGames** [PriestTheBeast/Compressed-Factory#7] opened 2017-12-10 23:28 UTC
**Bug #1**  this bug is more recurring
energy outlet was 'desynced' from the factory's energy buffer, when breaking the outlet while this desync is active a crash happens. Resolve found was to turn off then back on the factory as well as using shears on an active controller.
https://gist.github.com/mallrat208/f902f7de14509f03e81fad55d3d02afe

**Bug #2** this bug was found in a solo world, crash log is blank
In a solo, creative world several attempts at making a 'three layered' structure, after several failed attempts made a successful 3 by 3 by 3 factory in an attempt to reach tier 3 to test a theory (_Bug #3_) when entering this 3 by 3 by 3 factory of tier 1 the solo instance crashes. Again Crash log was completely blank.

**Bug #3** This involves Tier 3
When a Tier 3 factory is made the walls generate as minecraft dirt with Compressed Factory mod unbreakable lit stone as well as minecraft bedrock. (See image) When leaving this level and creating a new size or reconnecting (turn off and on the factory) the factory refuses to connect as the minecraft dirt and bedrock were not removed when the factory reset its walls. no matter how large the structure. 

> You are probably trying to create a factory that would make it so the walls of the factory would replace blocks you previously put there

![2017-12-10_16 08 27](https://user-images.githubusercontent.com/33973064/33810817-f654078e-ddc6-11e7-8808-cb59f91a7d79.png)

**Comment by Vaygrim** [comment] 2017-12-10 23:37
I'm getting the same issue with Tier 3 Factories. This is what I get after creating a brand new one and stepping into it.
![screenshot 2017-12-10 17 35 03](https://user-images.githubusercontent.com/4295188/33810878-a83fb71e-ddd0-11e7-85a0-f373f462a099.png)

**Comment by PriestTheBeast** [comment] 2017-12-17 15:31
This is extremely strange.
I will look into it.

**Comment by PriestTheBeast** [comment] 2017-12-17 19:33
Bug 1: is fixed in new update.
Bug 2: i have no clue, i did a maximum sized compressor, 3 layers, all seemed fine.
Bug 3: i never create dirt in the code, in the tier 3 i used bedrock, tested it and saw no dirt.
I think bug 2 and 3 must be a conflict with some other mod.
Anyway, i don't think i can solve those bugs that i can't reproduce like mysterious dirt appearing from nowhere and 3 layers crashing with blank crash logs.
When i have time i might download vaygrim's modpack to test.

**Comment by FoxBotGames** [comment] 2017-12-17 19:44
I'm not concerned about Bug 2 as this has so far been unable to reproduce, might have been a world issue. 
Bug 1 im glad is fixed
Bug 3.... I will have to get back on that

**Closed** 2018-01-10 14:40 UTC
